eureka:
  client:
    service-url:
      efaultZone: http://q-ring:19000/eureka/

server:
  port: 19040

spring:
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_PROD_HOST}
      port: ${REDIS_PROD_PORT}

  datasource:
    url: ${DB_PROD_URL}
    username: ${DB_PROD_USER}
    password: ${DB_PROD_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_PROD_URL}
    consumer:
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: '*'
    topic:
      reservation-create-event: reservation-create-event-topic
      reservation-update-event: reservation-update-event-topic
      userinfo-send-event: userinfo-send-event-topic
      queue-alarm-event: queue-alarm-event-topic
      queue-create-fail-event: queue-create-fail-event-topic
      queue-delete-fail-event: queue-delete-fail-event-topic

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}